# Generated by Django 5.2.2 on 2025-06-11 17:41

import backend.uploads.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=backend.uploads.models.Upload.upload_to_uuid)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
