# Generated by Django 5.2.2 on 2025-06-11 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='tenant',
        ),
    ]
