# Generated by Django 5.2.2 on 2025-06-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_remove_upload_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='name',
            field=models.CharField(blank=True, default='test', max_length=255, null=True),
        ),
    ]
