# Generated by Django 6.0 on 2026-09-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_alter_upload_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
