# Generated by Django 6.0 on 2025-12-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_entries', '0001_initial'),
        ('tagging', '0002_clienttag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualentry',
            name='tags',
        ),
        migrations.AddField(
            model_name='manualentry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='manual_entries', to='tagging.tag'),
        ),
    ]
