# Generated by Django 6.0 on 2025-12-28 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clipping', '0002_alter_clip_x_alter_clip_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClipTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clip_tags', to='clipping.clip')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clip_tags', to='tagging.tag')),
            ],
        ),
    ]
