# Generated by Django 5.2.2 on 2025-06-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='clip',
            name='y',
            field=models.FloatField(),
        ),
    ]
