# Generated by Django 6.0 on 2025-12-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipping', '0002_alter_clip_x_alter_clip_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='page_number',
            field=models.IntegerField(default=1),
        ),
    ]
